#ifndef COREPLATFORM_GLOBAL_H
#define COREPLATFORM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COREPLATFORM_LIBRARY)
#  define COREPLATFORMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COREPLATFORMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COREPLATFORM_GLOBAL_H
